#!/usr/bin/env python3
"""
Pinterest pin image generator.

Renders a 1000x1500 PNG per pin entry using Pillow:
  - Top brand bar: errorcodefixes.com on accent color
  - Big bold title (brand + code) center top half
  - Subtitle ("Complete Fix Guide" / "Diagnostic Steps Inside")
  - "Save for later" hint in lower corner
  - Bottom accent bar with domain

Pulls titles from the latest 2026-05-*_pins.md generated by
scripts/pinterest-pin-batch.py. Outputs to
growth-pipeline/pinterest/images/.

USAGE:
    python scripts/pinterest-pin-image-gen.py
    python scripts/pinterest-pin-image-gen.py --pins growth-pipeline/pinterest/2026-05-25_pins.md
"""

from __future__ import annotations

import argparse
import re
import sys
import textwrap
from pathlib import Path
from PIL import Image, ImageDraw, ImageFilter, ImageFont

ROOT = Path(__file__).resolve().parents[1]
PIN_DIR = ROOT / "growth-pipeline" / "pinterest"
OUT_DIR = PIN_DIR / "images"
WIDTH, HEIGHT = 1000, 1500

# Brand colors — orange/amber accent (matches Layout.astro theme-color #d97706)
ACCENT = (217, 119, 6)       # accent orange
DARK = (32, 24, 12)          # warm dark for backgrounds
LIGHT_BG = (250, 248, 244)   # cream off-white
TEXT_DARK = (35, 30, 22)
TEXT_MUTED = (110, 100, 88)
WHITE = (255, 255, 255)


def find_font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    """Pick the best available system font. Windows always has Arial."""
    candidates = (
        ["arialbd.ttf", "Arial Bold.ttf", "arial.ttf"]
        if bold
        else ["arial.ttf", "Arial.ttf"]
    )
    for name in candidates:
        for path in [
            f"C:/Windows/Fonts/{name}",
            f"/usr/share/fonts/truetype/dejavu/{name}",
            name,
        ]:
            try:
                return ImageFont.truetype(path, size)
            except Exception:
                continue
    return ImageFont.load_default()


def parse_pins(md_path: Path) -> list[dict]:
    """Extract title + destination URL from each pin section."""
    text = md_path.read_text(encoding="utf-8")
    pins = []
    for block in re.split(r"^\*\*Pin \d+:", text, flags=re.MULTILINE)[1:]:
        # First non-blank line is the long title; first matched URL is the destination
        first_line = block.lstrip().split("\n", 1)[0].rstrip("*").strip()
        # Trim trailing " - What It Means and How to Fix It" type suffix
        title = re.sub(r"\s*[-–—]\s*What.*$", "", first_line, flags=re.IGNORECASE).strip()
        url_m = re.search(r"https://errorcodefixes\.com/posts/([a-z0-9\-]+)/?", block)
        slug = url_m.group(1) if url_m else ""
        if title and slug:
            pins.append({"title": title, "slug": slug})
    return pins


def split_lines(text: str, font: ImageFont.FreeTypeFont, max_width: int) -> list[str]:
    """Word-wrap text to fit max_width given the font metrics."""
    words = text.split()
    if not words:
        return [text]
    lines: list[str] = []
    current = words[0]
    for w in words[1:]:
        trial = current + " " + w
        bbox = font.getbbox(trial)
        if bbox[2] - bbox[0] > max_width:
            lines.append(current)
            current = w
        else:
            current = trial
    lines.append(current)
    return lines


def draw_pin(title: str, slug: str, out_path: Path) -> None:
    img = Image.new("RGB", (WIDTH, HEIGHT), LIGHT_BG)
    draw = ImageDraw.Draw(img)

    # Top accent bar with brand name
    draw.rectangle([(0, 0), (WIDTH, 90)], fill=ACCENT)
    brand_font = find_font(36, bold=True)
    draw.text((50, 26), "ERRORCODEFIXES.COM", fill=WHITE, font=brand_font)

    # Right-side subtitle in top bar
    subtitle_font = find_font(22, bold=False)
    sub = "Free Technician Fix Guides"
    sub_w = subtitle_font.getbbox(sub)[2]
    draw.text((WIDTH - sub_w - 50, 35), sub, fill=WHITE, font=subtitle_font)

    # Big numeric badge
    badge_y = 160
    badge_size = 280
    draw.ellipse(
        [(WIDTH // 2 - badge_size // 2, badge_y),
         (WIDTH // 2 + badge_size // 2, badge_y + badge_size)],
        outline=ACCENT, width=10
    )
    pill_font = find_font(34, bold=True)
    pill_text = "FIX"
    pill_w = pill_font.getbbox(pill_text)[2]
    pill_height = 60
    pill_w_padded = pill_w + 60
    draw.rectangle(
        [
            (WIDTH // 2 - pill_w_padded // 2, badge_y + badge_size // 2 - pill_height // 2),
            (WIDTH // 2 + pill_w_padded // 2, badge_y + badge_size // 2 + pill_height // 2),
        ],
        fill=ACCENT,
    )
    draw.text(
        (WIDTH // 2 - pill_w // 2, badge_y + badge_size // 2 - 22),
        pill_text,
        fill=WHITE,
        font=pill_font,
    )

    # Headline (the title)
    headline_y = 540
    headline_size = 72
    while headline_size > 38:
        headline_font = find_font(headline_size, bold=True)
        lines = split_lines(title, headline_font, WIDTH - 100)
        if len(lines) <= 4:
            break
        headline_size -= 4
    line_h = int(headline_size * 1.18)
    for i, line in enumerate(lines):
        line_w = headline_font.getbbox(line)[2]
        draw.text(
            ((WIDTH - line_w) // 2, headline_y + i * line_h),
            line,
            fill=TEXT_DARK,
            font=headline_font,
        )

    # CTA section
    cta_y = HEIGHT - 350
    cta_font = find_font(34, bold=True)
    cta_text = "Diagnose. Fix. Get back to work."
    cta_w = cta_font.getbbox(cta_text)[2]
    draw.text(((WIDTH - cta_w) // 2, cta_y), cta_text, fill=TEXT_DARK, font=cta_font)

    sub_cta_font = find_font(26, bold=False)
    sub_cta = "Real OEM part numbers. Voltage and resistance ranges. No paywall."
    sub_cta_lines = split_lines(sub_cta, sub_cta_font, WIDTH - 120)
    for i, line in enumerate(sub_cta_lines):
        line_w = sub_cta_font.getbbox(line)[2]
        draw.text(
            ((WIDTH - line_w) // 2, cta_y + 60 + i * 35),
            line,
            fill=TEXT_MUTED,
            font=sub_cta_font,
        )

    # Bottom URL bar
    draw.rectangle([(0, HEIGHT - 110), (WIDTH, HEIGHT)], fill=DARK)
    url_font = find_font(38, bold=True)
    url_text = f"errorcodefixes.com"
    url_w = url_font.getbbox(url_text)[2]
    draw.text(
        ((WIDTH - url_w) // 2, HEIGHT - 80),
        url_text,
        fill=ACCENT,
        font=url_font,
    )
    save_font = find_font(20, bold=False)
    save_text = "📌 Save this pin for the next time it acts up"
    save_w = save_font.getbbox(save_text)[2]
    # Draw on the cream area just above the dark bar
    draw.text(
        ((WIDTH - save_w) // 2, HEIGHT - 145),
        save_text,
        fill=TEXT_MUTED,
        font=save_font,
    )

    img.save(out_path, "PNG", optimize=True)


def latest_pins_file() -> Path:
    candidates = sorted(PIN_DIR.glob("*_pins.md"), reverse=True)
    if not candidates:
        raise SystemExit("[!] No pin markdown files found in growth-pipeline/pinterest/")
    return candidates[0]


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--pins", help="path to pins.md file (default: latest)")
    p.add_argument("--limit", type=int, default=0, help="max pins to render")
    args = p.parse_args()

    md_path = Path(args.pins) if args.pins else latest_pins_file()
    print(f"[i] reading {md_path.name}")
    pins = parse_pins(md_path)
    if args.limit:
        pins = pins[: args.limit]
    print(f"[i] {len(pins)} pins to render")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for i, pin in enumerate(pins, 1):
        out_path = OUT_DIR / f"{pin['slug']}.png"
        draw_pin(pin["title"], pin["slug"], out_path)
        print(f"  [{i:>2}/{len(pins)}] {pin['slug']}.png")

    print(f"\n[+] {len(pins)} pin images written to {OUT_DIR}")
    print("    Upload to Pinterest with the descriptions from the .md file.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
